In [14]:
import numpy as np
from make_HB import b_dag,a_dag,HB
from qiskit import BasicAer
from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister

ImportError: attempted relative import with no known parent package

In [2]:
#examples usint SO2- to S02
S=[[0.9979,0.0646],[-0.0646,0.9979]]
delta=[-1.8830,0.4551]
omegaA=[943.3,464.7]
omegaB=[1178.1,518.8]
OhmA=np.diag(omegaA)
OhmB=np.diag(omegaB)


The following cell is a test bed for the binary qubit mapping functions described in make_HB

In [5]:
a_dag1=a_dag(4)
print(a_dag1)

[[[[1 1]
   [0 1]]

  [[0 0]
   [0 0]]]


 [[[0 0]
   [0 0]]

  [[0 0]
   [0 0]]]]


In [10]:
test=HB(S,omegaB,OhmA,OhmB,delta,4)


ValueError: non-broadcastable output operand with shape (2,2) doesn't match the broadcast shape (2,2,2,2)

In [4]:
b_dag1=b_dag(S,OhmA,OhmB,delta,L_max=4)
print(b_dag1)

[[[[0.22362909 0.        ]
   [0.0409658  0.        ]]

  [[0.         0.        ]
   [0.         0.        ]]]


 [[[0.22362909 0.        ]
   [0.0409658  0.        ]]

  [[0.22362909 0.        ]
   [0.0409658  0.        ]]]]


In [32]:
Ne=5 #the number of  qubits in register E. LIMITS RESOLUTIONS
Ns=5 #the number of  qubits in register S
backend = BasicAer.get_backend('unitary_simulator')

![SNOWFALL](c.png)

In [34]:
qE=QuantumRegister(Ne)
qS=QuantumRegister(Ns)

qc=QuantumCircuit(qE,qS)
qc.h(qE)
qc.barrier()

repetitions = 1
for counting_qubit in range(3):
    for i in range(repetitions):
        qpe.cp(math.pi/4, counting_qubit, 3); # This is CU
    repetitions *= 2
    
qc.draw()

┌───┐
q7_0: ┤ H ├
      ├───┤
q7_1: ┤ H ├
      ├───┤
q7_2: ┤ H ├
      ├───┤
q7_3: ┤ H ├
      ├───┤
q7_4: ┤ H ├
      └───┘
q8_0: ─────
           
q8_1: ─────
           
q8_2: ─────
           
q8_3: ─────
           
q8_4: ─────