In [2]:
import numpy as np
import math
from make_HB import b_dag,a_dag,HB
from qiskit import BasicAer
from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister
from qiskit.extensions import HamiltonianGate
import pandas as pd

In [3]:
#examples usint SO2- to S02
S=[[0.9979,0.0646],[-0.0646,0.9979]]
delta=[-1.8830,0.4551]
omegaA=[943.3,464.7]
omegaB=[1178.1,518.8]
OhmA=np.diag(omegaA)
OhmB=np.diag(omegaB)


In [4]:
test=HB(S,omegaB,OhmA,OhmB,delta,4) #the error is in this function



1
2
3
[[[[1 1]
   [0 1]]

  [[0 0]
   [0 0]]]


 [[[0 0]
   [0 0]]

  [[0 0]
   [0 0]]]]


UnboundLocalError: local variable 'a_dag_tot' referenced before assignment

In [27]:
Ne=4 #the number of  qubits in register E. LIMITS RESOLUTIONS
Ns=4 #the number of  qubits in register S NB must be the same as L max
backend = BasicAer.get_backend('unitary_simulator')

![SNOWFALL](c.png)

# The cell below constructs the circuit above (figure from the oringal paper)


In [28]:
qE=QuantumRegister(Ne)
qS=QuantumRegister(Ns)

qc=QuantumCircuit(qE,qS)
qc.h(qE)
qc.barrier()

U=HamiltonianGate(test,2*math.pi)

def qft_dagger(qc, n):
    """
    extracted from opensource qiskit textbook
    https://qiskit.org/textbook/ch-algorithms/quantum-phase-estimation.html

    n-qubit QFTdagger the first n qubits in circ"""
    # Don't forget the Swaps!
    for qubit in range(n//2):
        qc.swap(qubit, n-qubit-1)
    for j in range(n):
        for m in range(j):
            qc.cp(-math.pi/float(2**(j-m)), m, j)
        qc.h(j)
        
qft_dagger(qc,Ne)
qc.draw()

ExtensionError: 'Input matrix is not Hermitian.'